{{- if .Values.upgradeCenter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: bold-upgrade-center-playwright
  {{- if eq $.Release.Namespace "default" }}
  namespace: {{ $.Values.namespace }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}_{{ .Chart.Version }}
    app.kubernetes.io/name: bold-upgrade-center-playwright
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  BOLD_ADMIN_USERNAME: {{ if .Values.rootUserDetails.email }}{{ .Values.rootUserDetails.email | quote }}{{ else }}{{ .Values.upgradeCenter.secret.adminUsername | quote }}{{ end }}
  BOLD_ADMIN_PASSWORD: {{ if .Values.rootUserDetails.password }}{{ .Values.rootUserDetails.password | quote }}{{ else }}{{ .Values.upgradeCenter.secret.adminPassword | quote }}{{ end }}
{{- end }}
